// import { FlashMessage } from "./flash-message";
// import { getFlashMessage, setFlashMessage } from "./flash-action";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <FlashMessage
          key={new Date().valueOf()}
          setFlashAction={setFlashMessage}
          getFlashAction={getFlashMessage}
        /> */}
        {children}
      </body>
    </html>
  );
}
